name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello
        run: |
          echo "hello world"
      - name: python-script
        run: |
           pip install -r requirements.txt
           python ci.py
  io:
    runs-on: ubuntu-latest
    steps:
    - name: hello 
      id: set-var
      shell: python
      run: |
        import os
        with open(os.environ['GITHUB_OUTPUT'],'a') as f:
          print(f'VAL_FOUND=true',file=f)
    - name: print value
      run: echo "the value is ${{ steps.set-var.outputs.VAL_FOUND }}"
          
